export const MEME_LIST_REQUEST = "MEME_LIST_REQUEST";
export const MEME_LIST_SUCCESS = "MEME_LIST_SUCCESS";
export const MEME_LIST_FAIL = "MEME_LIST_FAIL";

export const MEME_BY_ID_REQUEST = "MEME_BY_ID_REQUEST";
export const MEME_BY_ID_SUCCESS = "MEME_BY_ID_SUCCESS";
export const MEME_BY_ID_FAIL = "MEME_BY_ID_FAIL";

export const MEME_UPLOAD_REQUEST = "MEME_UPLOAD_REQUEST";
export const MEME_UPLOAD_SUCCESS = "MEME_UPLOAD_SUCCESS";
export const MEME_UPLOAD_FAIL = "MEME_UPLOAD_FAIL";
export const MEME_UPLOAD_RESET = "MEME_UPLOAD_RESET";

export const MEME_UPDATE_REQUEST = "MEME_UPDATE_REQUEST";
export const MEME_UPDATE_SUCCESS = "MEME_UPDATE_SUCCESS";
export const MEME_UPDATE_FAIL = "MEME_UPDATE_FAIL";
export const MEME_UPDATE_RESET = "MEME_UPDATE_RESET";
